name: Check Links

on:
  push:
    branches:    
    - '**'

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check Links
        run: |
          bash -x ./check_links.sh
