name: Check Links

on:
  push:
    branches:    
    - '**'

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check Links
        run: |
          export LINKS="$(grep -r 'https://' ./docs | grep -oP 'https://.*' | sed 's| .*||;s|).*||;s|`.*||' | grep -v yourdomain)"
          echo "Found $LINKS"
          echo '#####################################################'
          mapfile -t LINKS <<< "$LINKS"
          for link in "${LINKS[@]}"
          do
            if [ "$(curl -sLI "$link" -o /dev/null -w "%{http_code}\n")" != 200 ]; then
                echo "$link is invalid."
                export INVALID=1
            fi
            sleep 2
          done
          if [ -n "$INVALID" ]; then
            exit 1
          fi
