name: Check Links

on:
  push:
    branches:    
    - '**'

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check Links
        run: |
          export LINKS="$(grep -r 'http' ./docs | grep -oP 'http.*' | sed 's| .*||;s|).*||;s|`.*||')"
          echo "Found $LINKS"
          echo '#####################################################'
          mapfile -t LINKS <<< "$LINKS"
          for link in "${LINKS[@]}"
          do
            if echo "$link" | grep -q "yourdomain" || echo "$link" | grep -q "geizhals.eu"
            then
                echo "Not testing $link"
                continue
            fi
            if [ "$(curl -sLI "$link" -o /dev/null -w "%{http_code}\n")" != 200 ]; then
                echo "$link is invalid."
                export INVALID=1
            fi
          done
          if [ -n "$INVALID" ]; then
            exit 1
          fi
